apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: notary-initial-registration
  annotations:
    flux.weave.works/automated: "false"
  namespace: supplychain-ns
spec:
  releaseName: notary-initial-registration
  chart:
    path: platforms/r3-corda/charts/notary-initial-registration
    git: ssh://git@github.com/peterderooijaccenture/blockchain-automation-framework.git
    ref: local
  values:
    nodeName: notary
    replicas: 1
    metadata:
      namespace: supplychain-ns  
    image:
      containerName: index.docker.io/hyperledgerlabs/corda:4.1-linuxkit
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
      doormanCertAlias: 192.168.99.113
      networkmapCertAlias: 192.168.99.113
    nodeConf:
      p2p:
        url: notary.supplychain-ns
        port: 10002
      ambassadorAddress: notary.develop.local.com:10010
      rpcSettings:
        useSsl: false
        standAloneBroker: false
        address: "0.0.0.0:10003"
        adminAddress: "0.0.0.0:10005"
        ssl:
          certificatesDirectory: na-ssl-false
          sslKeystorePath: na-ssl-false
          trustStoreFilePath: na-ssl-false
      legalName: O=Notary,OU=Notary,L=London,C=GB #use peer-node level subject for legalName
      messagingServerAddress:
      jvmArgs:
      systemProperties:
      sshd:
        port:
      exportJMXTo:
      transactionCacheSizeMegaBytes: 8
      attachmentContentCacheSizeMegaBytes: 10
      attachmentCacheBound: 1024
            
      notary:
        validating: false
       
      detectPublicIp: false
      database:
        transactionIsolationLevel: READ_COMMITTED
        exportHibernateJMXStatistics: false
      dbUrl: notarydb
      dbPort: 9101
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dataSourceUrl: "jdbc:h2:tcp://notarydb:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
      jarPath: "/data/corda-workspace/h2/bin"
      networkMapURL: https://192.168.99.113:30040
      doormanURL: http://192.168.99.113:30030
      compatibilityZoneURL:
      jarVersion: "4.0"
      devMode: false
      env:
        - name: JAVA_OPTIONS
          value: -Xmx512m
        - name: CORDA_HOME
          value: /opt/corda
        - name: BASE_DIR
          value: /base/corda
    credentials:
      dataSourceUser: sa
      rpcUser:
        - name: notaryoperations
          permissions: [ALL]

    volume:
      baseDir: /base/corda
    resources:
      limits: "512Mi"
      requests: "512Mi"
    
    service:
      type: ClusterIP
      p2p:
        port: 10002
        targetPort: 10002
      rpc:
        port: 10003
      rpcadmin:
        port: 10005

    vault:
      address: http://amac02xjhz7jg5j:8200
      role: vault-role
      authpath: cordanotary
      serviceaccountname: vault-auth
      dbsecretprefix: notary/credentials/database
      rpcusersecretprefix: notary/credentials/rpcusers
      tokensecretprefix: notary/credentials/vaultroottoken
      keystoresecretprefix: notary/credentials/keystore
      certsecretprefix: notary/certs
        
    healthcheck:
      readinesscheckinterval: 10
      readinessthreshold: 15
